import 'package:flutter/material.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedInputtWidget.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedInputtWidget1.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedBIENVENIDOAJMASWidget.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedBottonWidget.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedDescarga1Widget.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedINGRESESUNUMERODERESIVOPORFAVORWidget.dart';
import 'package:flutterapp/actfinalapp/generatedloginwidget/generated/GeneratedFrame1Widget.dart';

/* Frame login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 229, 229, 229),
                ),
              ),
              Positioned(
                left: -2.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 500.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 4.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 406.0,
                height: 495.0,
                child: GeneratedDescarga1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 459.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 39.0,
                child: GeneratedBIENVENIDOAJMASWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 68.0,
                child: GeneratedINGRESESUNUMERODERESIVOPORFAVORWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputtWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 695.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputtWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 22.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 803.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBottonWidget(),
              )
            ]),
      ),
    ));
  }
}
