import 'package:flutter/material.dart';
import 'package:flutterapp/actfinalapp/generatedpagoswidget/generated/GeneratedMenuinferiorWidget1.dart';
import 'package:flutterapp/actfinalapp/generatedpagoswidget/generated/GeneratedInputtWidget4.dart';
import 'package:flutterapp/actfinalapp/generatedpagoswidget/generated/GeneratedInputtWidget5.dart';
import 'package:flutterapp/actfinalapp/generatedpagoswidget/generated/GeneratedInputtWidget6.dart';
import 'package:flutterapp/actfinalapp/generatedpagoswidget/generated/GeneratedInputtWidget7.dart';

/* Frame pagos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 408.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputtWidget4(),
              ),
              Positioned(
                left: 9.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputtWidget5(),
              ),
              Positioned(
                left: 9.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputtWidget6(),
              ),
              Positioned(
                left: 9.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputtWidget7(),
              )
            ]),
      ),
    ));
  }
}
