import 'package:flutter/material.dart';
import 'package:flutterapp/actfinalapp/generatedinputtwidget2/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/actfinalapp/generatedinputtwidget2/generated/GeneratedIngresaelnumerodecuentaWidget1.dart';

/* Component inputt
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputtWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 60.0,
              child: GeneratedRectangle1Widget2(),
            ),
            Positioned(
              left: 20.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 208.0,
              height: 22.0,
              child: GeneratedIngresaelnumerodecuentaWidget1(),
            )
          ]),
    ));
  }
}
