import 'package:flutter/material.dart';
import 'package:flutterapp/actfinalapp/generatedmenuinferiorwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/actfinalapp/generatedmenuinferiorwidget/generated/GeneratedPagoWidget.dart';
import 'package:flutterapp/actfinalapp/generatedmenuinferiorwidget/generated/GeneratedClienteWidget.dart';
import 'package:flutterapp/actfinalapp/generatedmenuinferiorwidget/generated/GeneratedRectangle4Widget.dart';

/* Component menu inferior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuinferiorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 408.0,
      height: 90.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 245, 245, 245),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 13.0,
              right: null,
              bottom: null,
              width: 408.0,
              height: 77.0,
              child: GeneratedRectangle4Widget(),
            ),
            Positioned(
              left: 322.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 40.0,
              height: 53.0,
              child: GeneratedPagoWidget(),
            ),
            Positioned(
              left: 39.0,
              top: 26.0,
              right: null,
              bottom: null,
              width: 53.0,
              height: 50.79998779296875,
              child: GeneratedClienteWidget(),
            ),
            Positioned(
              left: 179.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 68.22222137451172,
              child: GeneratedHomeWidget(),
            )
          ]),
    ));
  }
}
